export const tagTypes = {
  user: "User",
  bid: "Bid",
  offer: "Offer",
  order: "Order",
  task: "Task",
  message: "Message",
  notification: "Notification",
  notificationCount: "notificationCount",
  sellCar: "SellCar",
  contactPaper: "ContactPaper",
  purchasedCar: "purchasedCar",
  product: "Product",
  shelter: "Shelter",
  userProfile: "UserProfile",
  petProfile: "PetProfile",
};

export const tagTypesList = [
  tagTypes.user,
  tagTypes.bid,
  tagTypes.offer,
  tagTypes.order,
  tagTypes.task,
  tagTypes.message,
  tagTypes.notification,
  tagTypes.notificationCount,
  tagTypes.sellCar,
  tagTypes.contactPaper,
  tagTypes.purchasedCar,
  tagTypes.product,
  tagTypes.shelter,
  tagTypes.userProfile,
  tagTypes.petProfile,
];
